ALTER TABLE KITAP ADD TARIH DATE;

--1. hangi kitabýn hangi yayýnevinden basýldýðýný gösteren sorgu.

SELECT K.KITAP_ADI,Y.YAYINEVI_ADI  FROM KITAP K
INNER JOIN YAYINEVI Y ON Y.YAYINEVI_ID = K.YAYINEVI_ID;

--2. HANGÝ kitabýn HANGÝ YAZARIN YAZDIÐI

SELECT K.KITAP_ADI, (Y.YAZAR_ADI ||' ' || Y.YAZAR_SOYADI) "YAZAR ADI SOYADI" FROM KITAP K
INNER JOIN YAZAR Y ON Y.YAZAR_ID = K.YAZAR_ID;

--3. hangi yazarýn hangi yayýnevinden kitap çýkarttýðý

select (Y.YAZAR_ADI ||' ' || Y.YAZAR_SOYADI) "YAZAR ADI SOYADI" , k.kýtap_adý, yay.yayýnevý_adý from YAYINEVI yay
INNER JOIN KITAP K on k.YAYINEVI_ID = yay.YAYINEVI_ID
ýnner JOIN YAZAR Y ON k.yazar_ýd = y.yazar_ýd

--4. HANGI YAYINEVININ KAÇ TANE KITABI OLDUÐU VE HANGÝ YAZARA AÝT OLDUÐU

SELECT YAY.YAYINEVI_ADI, y.yazar_adý, COUNT(k.kýtap_ýd) "KITAP SAYISI"  FROM YAYINEVI YAY 
INNER JOIN KITAP K on k.YAYINEVI_ID = yay.YAYINEVI_ID
INNER JOIN YAZAR Y ON k.YAZAR_ID = Y.YAZAR_ID
GROUP BY yay.yayýnevý_adý, y.yazar_adý


-- COMBÝNE ÖRNEKLERÝ
-- YAZAR VE YAYINEVI EMAILLERÝNÝ BÝRLEÞTÝRME
select * from YAYINEVI
select * from yazar
INSERT INTO YAYINEVI(YAYINEVI_ID, YAYINEVI_ADI,YAYINEVI_EMAIL, YAYINEVI_TEL, ADRES)VALUES(7,'deneme', 'ayniemail@ayni.COM', '8754343433', 'trabzon');
INSERT INTO YAZAR(YAZAR_ID, YAZAR_ADI, YAZAR_SOYADI, YAZAR_EMAIL, YAZAR_TEL) VALUES(8,'DENEME','deneme','ayniemail@ayni.COM','2122334534');

--1
SELECT * FROM
(
SELECT YAYINEVI_EMAIL "EMAIL" FROM YAYINEVI
UNION
SELECT YAZAR_EMAIL "EMAIL" FROM YAZAR
)
ORDER BY EMAIL;

--2
SELECT * FROM
(
SELECT YAYINEVI_EMAIL "EMAIL" FROM YAYINEVI
UNION all
SELECT YAZAR_EMAIL "EMAIL" FROM YAZAR
)
ORDER BY EMAIL;

--3
SELECT * FROM
(
SELECT YAYINEVI_EMAIL "EMAIL" FROM YAYINEVI
INTERSECT
SELECT YAZAR_EMAIL "EMAIL" FROM YAZAR
)
ORDER BY EMAIL;

--4 
SELECT * FROM
(
SELECT YAYINEVI_EMAIL "EMAIL" FROM YAYINEVI
MINUS
SELECT YAZAR_EMAIL "EMAIL" FROM YAZAR
)
ORDER BY 1;

SELECT TRIM(YAZAR_ADI) FROM YAZAR