--1CONCAT
--KÝTAP ADIYLA YAZARIN ÝSÝMLERÝNÝ BÝRLEÞTÝRELÝM.

SELECT CONCAT(K.KITAP_ADI,CONCAT(' ',Y.YAZAR_ADI)) FROM KITAP K
INNER JOIN YAZAR Y ON Y.YAZAR_ID = K.YAZAR_ID;

--2LENGTH 
--KÝTAP ADI VE UZUNLUÐU
SELECT KITAP_ADI, LENGTH(KITAP_ADI)"UZUNLUÐU"  FROM KITAP

-- YAZAR TELEFON NUMARASI 10 HANEDEN FARKLI OLAN

SELECT YAZAR_TEL FROM YAZAR WHERE LENGTH(YAZAR_TEL)<>10

--3 SUBSTR
--USTTEKÝ 1. SORGUYU ÝSTENÝLEN ÞEKÝLDE KELÝME ALALIM

SELECT SUBSTR(CONCAT(K.KITAP_ADI,CONCAT(' ',Y.YAZAR_ADI)),-5,4) FROM KITAP K
INNER JOIN YAZAR Y ON Y.YAZAR_ID = K.YAZAR_ID;

--4 INSTR
SELECT YAYINEVI_ADI, INSTR(YAYINEVI_ADI,'A',2) "KACINCI HARF" FROM YAYINEVI

--5 LPAD
select LPAD(ADRES,15,'I') "EKLEDÝK" from YAYINEVI where ADRES='ISTANBUL';

--6 RPAD
SELECT RPAD(FIYAT,3,00) FROM KITAP

--7 TRIM
select KITAP_ADI, TRIM('A' FROM KITAP_ADI) FROM KITAP

--8 REPLACE
select YAYINEVI_EMAIL, REPLACE(YAYINEVI_EMAIL,'@','%') from YAYINEVI; 

--9 LOWER
SELECT LOWER(YAZAR_ADI) FROM YAZAR

SELECT INITCAP(yazar_adý) FROM YAZAR

--10 ROUND TRUNC
select FIYAT, ROUND(FIYAT) from KITAP;
select FIYAT, TRUNC(FIYAT) from KITAP;
select FIYAT, TRUNC(FIYAT,4) from KITAP;

--11 TO CHAR

select * from KITAP where to_char(TARIH,'YYYY') IN (1993,1998) ;

--12 TO DATE

select * from KITAP where TARIH > to_DATE ('1993','YYYY')  ;

--13   
select  
    rank() OVER(PARTITION BY KITAP_ID ORDER BY FIYAT ) 
    rank,  
    KITAP_ID,     
    KITAP_ADI,  
    FIYAT 
from  KITAP ;


--14

select  
    row_number() OVER(ORDER BY FIYAT DESC ) 
    row_num,  
    KITAP_ADI,  
    FIYAT 
from KITAP; 

--15 
select KITAP_ID, FIYAT WRONG_VALUE, LAG(FIYAT,1) over (order by KITAP_ID) ACTUAL_VALUE from KITAP;